### ISSUE TITLE
linux部署数据库配置报错

### ISSUE THREAD

**Issue by superabbite1** [RainyGao-GitHub/DocSys#22]
linux部署的时候 第一次打开网站 提示配置数据库，提示这个错误，是数据库密码不对还是什么问题

![QQ截图20211204130236](https://user-images.githubusercontent.com/79433125/144697888-fae379bd-c2e0-47df-804d-ba770d7eb722.png)

**Comment by RainyGao-GitHub** [comment]
请先检查以下内容
1. 是否为root用户启动
2. 检查mysql是否启动正常（查看mysql的errorlog文件）
3. 建议使用2.02.18版本
