### ISSUE TITLE
winserver下超级管理员删除视频失败

### ISSUE THREAD

**Issue by ruoxia** [RainyGao-GitHub/DocSys#30]
![image](https://user-images.githubusercontent.com/18041591/200532839-444513e0-1b8f-4c94-956f-d9a9cd78a0a6.png)
![image](https://user-images.githubusercontent.com/18041591/200533066-c482f293-66ea-44ef-93aa-3e6d70ab76bf.png)

**Comment by RainyGao-GitHub** [comment]
在播放的时候不能删除
